# 範例配置文件 - YAML格式
name: "張三"
date: "2024-08-19"
city: "台北市"
department: "資訊部"
position: "軟體工程師"
salary: "60000"

# 多行文字範例
description: |
  負責系統開發與維護
  包含前端與後端開發
  具備敏捷開發經驗

address: |
  台北市信義區
  信義路五段7號
  10樓

notes: >
  這位員工表現優異，
  具有良好的團隊合作精神，
  建議給予晉升機會。

# 公司資訊
company:
  name: "ABC科技公司"
  address: "台北市信義區信義路五段7號"
  phone: "02-1234-5678"

# 專案資訊  
project:
  name: "文件填充系統"
  startDate: "2024-08-01"
  endDate: "2024-12-31"