# 臨床試驗計畫配置文件
# 基本資訊
計畫名稱: "AI驅動之腹部創傷輔助診斷系統"
Title: "AI驅動之腹部創傷輔助診斷系統之驗證"
計畫主持人: "王雅婷 醫師"
機構名稱: "市立綜合醫院"
單位: "影像醫學部"
Email: "yt.wang@citygeneral.org.tw"
使用藥物器材: "AI驅動之腹部創傷輔助診斷軟體"
試驗委託者姓名: "未來健康創新股份有限公司"
試驗委託者地址: "大都會市科技園區創新路123號"
版本: "1.1"
日期: "2024-08-20"

填寫人: "王雅婷 醫師"
電話: "0912-345-678"

Date_Start: "2025-03-01"
Date_End: "2027-02-28"


# 試驗內容
摘要研究背景: |
  腹部創傷是導致高發病率和死亡率的主要原因。快速準確的診斷對於改善患者預後至關重要。雖然電腦斷層掃描是黃金標準，但影像判讀耗時且存在變異性。本研究旨在探討使用AI輔助系統以提高診斷準確性。
摘要研究目的: |
  主要目的：驗證此AI輔助診斷系統在不同醫療中心腹部電腦斷層掃描資料上的效能與準確性。次要目的：評估該系統在臨床應用中的實用性，並收集使用者回饋以供未來改進。
摘要研究設計: |
  本研究為一項回溯性、多中心的研究，將使用現有的腹部電腦斷層掃描影像資料，不涉及招募新病患。
摘要受試者: |
  本研究將納入自2018年1月1日至2023年12月31日期間，年滿18歲並接受腹部電腦斷層掃描的患者之匿名影像。資料集將包含1200個案例（300例腹部創傷陽性，900例陰性）。
摘要研究方法: |
  將透過電腦斷層報告及ICD-10編碼篩選案例，並經人工審核。DICOM檔案將轉換為匿名的NIfTI格式。AI系統將分析影像，其結果將與資深放射科醫師的判讀結果進行比對。
摘要副作用處理: |
  本研究為回溯性研究，使用現有資料，因此無直接的病患副作用需要處理。
摘要統計分析: |
  本研究將計算敏感度、特異度、陽性預測值、陰性預測值及ROC曲線下面積（AUC），以評估模型的效能。

摘要: |
  本研究為一項針對腹部創傷AI輔助診斷系統的多中心驗證。該系統利用深度學習模型自動識別腹部電腦斷層掃描影像中的創傷跡象。我們的目標是納入1200個回溯性案例，以評估模型的準確性與臨床實用性。

試驗主題背景: |
  此AI模型旨在協助放射科醫師快速準確地診斷腹部創傷。目標是減少診斷錯誤，並縮短重傷患者的治療時間。此次多中心驗證是該模型進入臨床應用前的關鍵步驟。

試驗目的: "在來自多家機構的多樣化腹部電腦斷層掃描資料集上，驗證此AI輔助診斷系統的效能與準確性。"
# 試驗方法:
選擇標準: |
  納入條件：年滿18歲，且於2018年1月1日至2023年12月31日期間因創傷接受腹部電腦斷層掃描的患者。將同時納入腹部創傷陽性與陰性案例。

排除標準: |
  排除條件：影像品質因嚴重移動假影或其他問題而無法進行診斷者。

受試者數目: |
  共1200例匿名患者掃描影像（300例陽性，900例陰性）。

知情同意: |
  本研究為匿名資料的回溯性研究，因此無需向新受試者取得知情同意。

試驗設計: |
  一項回溯性、多中心、非隨機、非盲性的驗證研究。

實施方法: |
  1. 資料獲取與匿名化。 2. AI模型處理電腦斷層掃描影像。 3. AI輸出結果與專家醫師報告進行比對。 4. 效能指標的統計分析。

試驗期限及預計進度: |
  2025年3月1日 至 2027年2月28日

追蹤復健計畫: |
  不適用，此為回溯性研究。

評估指標: |
  主要效能指標為敏感度、特異度、準確度及ROC曲線下面積（AUC）。

統計方法: |
  將採用標準的診斷準確性統計方法，包含所有效能指標的信賴區間計算。

預期效益: |
  成功的驗證將證明此AI輔助系統的臨床實用價值，有潛力在急診環境中實現更快、更準確的腹部創傷診斷。

可能傷害標準: |
  本研究使用匿名的回溯性資料，對患者無直接風險。

回報方式: |
  任何潛在的資料外洩或安全事件，將於15天內向倫理審查委員會（IRB）及委託機構報告。

處理方式: |
  所有資料將在安全的加密環境中處理，僅授權研究人員得以存取。資料將於研究結束後保留5年，屆時將安全刪除。

藥品設備: |
  產品名稱：創傷診斷輔助系統（DAT）。適應症：用於偵測電腦斷層掃描影像中的腹部創傷跡象。製造商：未來健康創新股份有限公司。

參考文獻: |
    1. 陳氏等。《醫學影像分析之深度學習》。醫學影像期刊，2021年。 2. 施氏等。《腹部創傷之電腦斷層掃描》。今日放射學，2019年。

不良事件處理方式: |
  不適用於回溯性研究，預期不會發生不良事件。

偏離計畫處理方式: |
  任何偏離已核准計畫書之情事將被記錄並向倫理審查委員會報告，包含資料品質、納入/排除條件或分析方法等問題。

危險評估說明: |
  本研究為回溯性設計，不涉及任何新的醫療程序、輻射暴露或其他對患者的介入措施。主要風險為潛在的資料隱私外洩，已透過強化的匿名化與安全協議加以控制。